'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '~/components/Navbar'
import Footer from '~/components/Footer'
import { useEffect } from 'react'
import { initFlowbite } from 'flowbite'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  useEffect(() => {
    initFlowbite()
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <script src='../../node_modules/flowbite/dist/flowbite.min.js'></script>
      </body>
    </html>
  )
}
